[package]
name = "crust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
rust-htslib = "0.47"
ndarray = "0.15.4"
rayon = "1.5.3"
anyhow = "1.0.45"